x : fine_grained_lock_list_test.cpp fine_grained_lock_list.cpp fine_grained_lock_list.h
	g++ -std=c++11 -o ./build/x fine_grained_lock_list_test.cpp fine_grained_lock_list.cpp fine_grained_lock_list.h -lpthread

clean :
	rm ./build/*