coarse_lock_list_test : coarse_lock_list_test.cpp coarse_lock_list.cpp coarse_lock_list.h
	g++ -std=c++11 coarse_lock_list_test.cpp coarse_lock_list.cpp coarse_lock_list.h -o build/coarse_lock_list_test -lpthread

clean:
	rm build/coarse_lock_list_test